name: newshub
version: 1
cron:
- description: cron_tech
  url: /phpfetcher/demo/fetch_news.php?class=tech
  schedule: "0 6 * * *"
- description: cron_ent
  url: /phpfetcher/demo/fetch_news.php?class=ent
  schedule: "5 6 * * *"
- description: cron_sports
  url: /phpfetcher/demo/fetch_news.php?class=sports
  schedule: "10 6 * * *"
- description: cron_finance
  url: /phpfetcher/demo/fetch_news.php?class=finance
  schedule: "15 6 * * *"
- description: cron_edu
  url: /phpfetcher/demo/fetch_news.php?class=edu
  schedule: "20 6 * * *"